// Code generated by "stringer -type NamedSign ."; DO NOT EDIT.

package go2way

import "fmt"

const _NamedSign_name = "QuestionDollarColon"

var _NamedSign_index = [...]uint8{0, 8, 14, 19}

func (i NamedSign) String() string {
	if i < 0 || i >= NamedSign(len(_NamedSign_index)-1) {
		return fmt.Sprintf("NamedSign(%d)", i)
	}
	return _NamedSign_name[_NamedSign_index[i]:_NamedSign_index[i+1]]
}
